name: firstaid_app
description: A simple first aid assistant app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Burns.jpeg
    - assets/images/chest_pain.jpeg
    - assets/images/choking.jpeg
    - assets/images/CPR_step1.jpeg
    - assets/images/CPR_step2.jpeg
    - assets/images/CPR_step3.jpeg
    - assets/images/CPR_step4.jpeg
    - assets/images/CPR.jpeg
    - assets/images/Cuts.jpeg
    - assets/images/Fracture.jpeg
    - assets/images/heart_attack.jpeg
    - assets/images/Nose_bleeding.jpeg
    - assets/images/seizures.jpeg
