name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.4"

      - name: Install dependencies
        run: flutter pub get

      - name: Build web app with correct base href
        run: flutter build web --base-href=/First_aid_system/

      - name: Add 404.html for GitHub Pages routing
        run: cp build/web/index.html build/web/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
